### ISSUE TITLE
Koth bugs

### ISSUE THREAD

**Issue by xComboed** [SubSide/KOTH#106]
Hello. I have bought the koth plugin but i got some issues. First the bossbar doest work. I have enabled it but it doest show himself or count. And if someone tries to cap the koth it sayd you are capping koth and after that it says nothing even if he stays there for 5 minutes while i have set it on 1 minute. And the scoreborad dont work to. Please tell me what i can do to let this work.

**Comment by SubSide** [comment]
The integrated bossbar only works for 1.9 and higher, if you want to use the bossbar at lower levels I can suggest Koth2Bossbar although it can be glitchy.

The fact the bossbar is crashing can also mean that it could cascade to the rest of the plugin.

I think that disabling the bossbar would fix your issues

**Comment by xComboed** [comment]
Thx for the tip. But now i got another issue cus if im capping and i get knocked others cant cap it. What can i do?

**Comment by xComboed** [comment]
and if it says i won the koth i get nothing i tried the option give loot instandly and i linked loot but both dont work while i made a lootbox. :(

**Comment by SubSide** [comment]
Are there any errors showing up in console?
