### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Lmmb74** [SubSide/KOTH#11]
Hi, I'm having troubles compiling the plugin. The log in maven is the following one:

> [INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/hooks/plugins/VanishHook.java:[5,25] package org.kitteh.vanish does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/hooks/plugins/VanishHook.java:[6,25] package org.kitteh.vanish does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/hooks/plugins/VanishHook.java:[16,13] cannot find symbol
  symbol:   class VanishManager
  location: class subside.plugins.koth.hooks.plugins.VanishHook
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionNormal.java:[10,40] package com.massivecraft.factions.entity
 does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionNormal.java:[11,40] package com.massivecraft.factions.entity
 does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionNormal.java:[12,40] package com.massivecraft.factions.entity
 does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionNormal.java:[19,9] cannot find symbol
  symbol:   class Faction
  location: class subside.plugins.koth.adapter.captypes.CappingFactionNormal
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionNormal.java:[21,33] cannot find symbol
  symbol:   class Faction
  location: class subside.plugins.koth.adapter.captypes.CappingFactionNormal
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionNormal.java:[57,12] cannot find symbol
  symbol:   class Faction
  location: class subside.plugins.koth.adapter.captypes.CappingFactionNormal
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionUUID.java:[10,33] package com.massivecraft.factions does not
 exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionUUID.java:[11,33] package com.massivecraft.factions does not
 exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionUUID.java:[12,33] package com.massivecraft.factions does not
 exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionUUID.java:[19,13] cannot find symbol
  symbol:   class Faction
  location: class subside.plugins.koth.adapter.captypes.CappingFactionUUID
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionUUID.java:[21,31] cannot find symbol
  symbol:   class Faction
  location: class subside.plugins.koth.adapter.captypes.CappingFactionUUID
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionUUID.java:[57,12] cannot find symbol
  symbol:   class Faction
  location: class subside.plugins.koth.adapter.captypes.CappingFactionUUID
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingKingdom.java:[9,38] package org.kingdoms.constants.kingdom does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingKingdom.java:[10,37] package org.kingdoms.constants.player does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingKingdom.java:[11,25] package org.kingdoms.main does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingKingdom.java:[12,33] package org.kingdoms.manager.game does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingKingdom.java:[19,13] cannot find symbol
  symbol:   class Kingdom
  location: class subside.plugins.koth.adapter.captypes.CappingKingdom
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingKingdom.java:[21,27] cannot find symbol
  symbol:   class Kingdom
  location: class subside.plugins.koth.adapter.captypes.CappingKingdom
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingKingdom.java:[59,12] cannot find symbol
  symbol:   class Kingdom
  location: class subside.plugins.koth.adapter.captypes.CappingKingdom
[INFO] 22 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.294 s
[INFO] Finished at: 2016-08-31T16:11:28-03:00
[INFO] Final Memory: 20M/226M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project KOTH: Compilation failure: Compilation failure:
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/hooks/plugins/VanishHook.java:[5,25] package org.kitteh.vanish does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/hooks/plugins/VanishHook.java:[6,25] package org.kitteh.vanish does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/hooks/plugins/VanishHook.java:[16,13] cannot find symbol
[ERROR] symbol:   class VanishManager
[ERROR] location: class subside.plugins.koth.hooks.plugins.VanishHook
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionNormal.java:[10,40] package com.massivecraft.factions.entity does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionNormal.java:[11,40] package com.massivecraft.factions.entity does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionNormal.java:[12,40] package com.massivecraft.factions.entity does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionNormal.java:[19,9] cannot find symbol
[ERROR] symbol:   class Faction
[ERROR] location: class subside.plugins.koth.adapter.captypes.CappingFactionNormal
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionNormal.java:[21,33] cannot find symbol
[ERROR] symbol:   class Faction
[ERROR] location: class subside.plugins.koth.adapter.captypes.CappingFactionNormal
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionNormal.java:[57,12] cannot find symbol
[ERROR] symbol:   class Faction
[ERROR] location: class subside.plugins.koth.adapter.captypes.CappingFactionNormal
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionUUID.java:[10,33] package com.massivecraft.factions does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionUUID.java:[11,33] package com.massivecraft.factions does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionUUID.java:[12,33] package com.massivecraft.factions does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionUUID.java:[19,13] cannot find symbol
[ERROR] symbol:   class Faction
[ERROR] location: class subside.plugins.koth.adapter.captypes.CappingFactionUUID
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionUUID.java:[21,31] cannot find symbol
[ERROR] symbol:   class Faction
[ERROR] location: class subside.plugins.koth.adapter.captypes.CappingFactionUUID
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingFactionUUID.java:[57,12] cannot find symbol
[ERROR] symbol:   class Faction
[ERROR] location: class subside.plugins.koth.adapter.captypes.CappingFactionUUID
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingKingdom.java:[9,38] package org.kingdoms.constants.kingdom does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingKingdom.java:[10,37] package org.kingdoms.constants.player does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/cap
types/CappingKingdom.java:[11,25] package org.kingdoms.main does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingKingdom.java:[12,33] package org.kingdoms.manager.game does not exist
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingKingdom.java:[19,13] cannot find symbol
[ERROR] symbol:   class Kingdom
[ERROR] location: class subside.plugins.koth.adapter.captypes.CappingKingdom
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingKingdom.java:[21,27] cannot find symbol
[ERROR] symbol:   class Kingdom
[ERROR] location: class subside.plugins.koth.adapter.captypes.CappingKingdom
[ERROR] /C:/Users/lauti/Desktop/GITHUB/KOTH/src/subside/plugins/koth/adapter/captypes/CappingKingdom.java:[59,12] cannot find symbol
[ERROR] symbol:   class Kingdom
[ERROR] location: class subside.plugins.koth.adapter.captypes.CappingKingdom
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project KOTH: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:858)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more

**Comment by SubSide** [comment]
Sadly you have to manually add some plugjns yourself, through properties I added the following plugins to the build path in libraries:

MassiveCore
Factions
FactionsUUID
Worldedit
Spigot 1.7.10
Lombok

The only reason I added maben is support for two different sligot versions at once
