### ISSUE TITLE
Error thrown out after koth capture

### ISSUE THREAD

**Issue by dotapurex1** [SubSide/KOTH#12]
Hello,

When a KoTH starts, it throws out this error: http://pastebin.com/KTgjJueW
Error when KoTH Ends: http://pastebin.com/RiknED8i

**Comment by SubSide** [comment]
Is this when it starts from a schedule or in general?

**Comment by SubSide** [comment]
As far as I can see it looks like the first error thrown is because said KoTH is already running.
The second one is not on my end, but on KothRewards end sadly
