### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by Twonox** [SubSide/KOTH#17]
What is the utility of Conquest scoreboard ?

**Comment by SubSide** [comment]
It's the scoreboard that will be shown when a conquest starts.

**Comment by Twonox** [comment]
But I have always the default scoreboard. It doesn't work.

**Comment by SubSide** [comment]
Sorry for reacting so late, my computer broke down. :(

Conquest is still a little bit a work in progress, I'm still figuring some bits out.

**Comment by SubSide** [comment]
Questions on the scoreboard should now be asked in its proper github.
