### ISSUE TITLE
Scoreboard Help

### ISSUE THREAD

**Issue by Rever** [SubSide/KOTH#18]
Hey,

I'm trying to make a custom scoreboard through the koth plugin. I do not have featherboard or any other scoreboard plugin installed. I am having difficulty setting it up and am getting this error...

"The received string is longer than the maximum allowed ( 35 > 19 )"

Even though this error makes perfect sense, I can't find a line that surpasses 19, except for the placeholders.

Thanks for the help

**Comment by SubSide** [comment]
Can you show me the config for the scoreboard?

**Comment by Twonox** [comment]
The colors codes are considered, take care.
Or you use placeholder who depend on PlaceholderAPI.

**Comment by Rever** [comment]
Thanks! I'm just not going to use scoreboard anymore, but @SubSide would I be able to request a feature from yourself? It may be beneficial to all and the feature should be very simple (In my mind it is)

**Comment by GodZain101** [comment]
i need help

**Comment by GodZain101** [comment]
I cant cap my koth

**Comment by SubSide** [comment]
Sorry for reacting so late, please open another issue for the request :)
