### ISSUE TITLE
Command feature

### ISSUE THREAD

**Issue by Twonox** [SubSide/KOTH#19]
Could you add command support to execute when koth start and when koth is finished.
Personally I would use that to enable and disable PvP in koth arena.

**Comment by SubSide** [comment]
Sorry for reacting so late, my computer broke down a couple of days ago.

If you have a developer for your server, you can ask them to execute a command on the KothStartEvent and KothEndEvent. Other that that, I don't think I will implement this feature as it's too specific and will propably not be used by a lot of people.
