### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Rono97** [SubSide/KOTH#20]
We recently installed KoTH onto our server, every time the server is started it throws this error

http://pastebin.com/Wc6P3w0x

And starts an unscheduled KoTH on restart of the server, this happens when no other plugins besides dependencies are installed

Server Version: https://gyazo.com/ab73d9b4f8c494a3969b061727049e48

Cheers - Rono

**Comment by GodZain101** [comment]
can some one help me

**Comment by SubSide** [comment]
Sorry, my laptop broke a couple of days ago, I'll get to it as soon as possible.

**Comment by SubSide** [comment]
Fixed in recent commit thanks for reporting!

12e771287a92be47c7abea8f33f9cefbd807e9eb
