### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by GodZain101** [SubSide/KOTH#21]
when I start koth 
it  don't start can you help me I create a koth a do /koth start and when I cap it say no one capping koth end
can you pls help me

**Comment by SubSide** [comment]
Before I answer your question, please don't respond to every issue... It's pretty annoying...

Now for your issue, did you select your area high enough?

**Comment by GodZain101** [comment]
how high it gat ti be???

**Comment by GodZain101** [comment]
you there

**Comment by GodZain101** [comment]
help me pls

**Comment by SubSide** [comment]
High enough for players to be able to stand inside of it, so like 5 blocks high
