### ISSUE TITLE
Multiple KoTHs at one time.

### ISSUE THREAD

**Issue by DiscoverCard** [SubSide/KOTH#22]
I have a KoTH schedule setup on my server and I also manually start KoTHs when players ask for them in chat. When I start a KoTH manually sometimes another one is scheduled to start so multiple KoTHs will be running at one time. I would like an option to be added in the config to be able to toggle having multiple KoTHs running at once.

**Comment by SubSide** [comment]
Added in recent commit

ba0d7db632919755757d2904c346a9c0c1ee7fa0
