### ISSUE TITLE
Scoreboard character limit

### ISSUE THREAD

**Issue by dartasen** [SubSide/KOTH#23]
Please add a scoreboard character limit because the client can't support more than 16 characters.
And if we use %capper% on scoreboard (alone on a line) it's annoying. 
If a faction has a name longer than 14 characters, when it replaces %capper% on scoreboard, it crashes.
And it's a real issue because faction's name are limited to 16 characters BUT it seems like the plugin already adds its own characters (maybe for the color) because 14 is enough to crash clients.

Exemple with the name "Scoreboardcrash" (15 characters)
Crash error : http://prntscr.com/d1hyza

PS : Sorry for my bad english.

**Comment by SubSide** [comment]
Added a config option for it in recent commit

811787a9da2d59c3e845e88b40a63ddd3b34b83c
