### ISSUE TITLE
Scoreboard FactionUUID / KOTH

### ISSUE THREAD

**Issue by Arkazium** [SubSide/KOTH#24]
Hello,

I bought your plugin 'KoTH and I use FactionUUID, yes, there is hook in the config.
But I actived the new_scoreboard of FactionUUID and when a koth start, the scoreboard of KoTH doesn't appear, so, the scoreboard of FactionUUID stays. It's possible to add an priority to KoTH plugin ? 

If you can fix this, I will can see the scoreboard of KoTH in fight :)

Thanks you,
Snyd3rs

**Comment by SubSide** [comment]
It is very hard to implement a scoreboard in Minecraft that also has compatibility with other plugins.
Currently the scoreboard of KoTH will overwrite the one of FactionsUUID or the other way around, without reenabling it afterwards.

I will soon try to implement a free third-party scoreboard system that will have more compatibility with plugins like FactionsUUID

**Comment by SubSide** [comment]
Questions on the scoreboard should now be asked in its proper github.
