### ISSUE TITLE
Koth Loot Full??

### ISSUE THREAD

**Issue by SquashMC** [SubSide/KOTH#25]
It looks like when I do /koth loot asmember when the loot is overfilled, nothing pops up.

**Comment by SubSide** [comment]
So when a player does /koth loot (equal as /koth loot asmember for admins), my plugin will do the following:

First it checks if there is a KoTH running, if so, show that loot.
If not, it checks if there is any KoTH's scheduled, if so, show that loot.
If not, it checks if you have defined a default loot in the config, if so, show that loot.

If all of the above fail, it will not show anything.


If one of the above IS true in your case, please contact me here again :)
