### ISSUE TITLE
Possibility to give loot directly to winning player?

### ISSUE THREAD

**Issue by Lezappen** [SubSide/KOTH#26]
After the person has been capping for 15minutes, nothing is worse than having an invisible player steal the loot and run off.

Two fixes can be done
    - Make the chest open just for the winning player.
    - Give the loot directly to the winning player.

**Comment by SubSide** [comment]
Both options should already be the case:
- ONLY the winner (this can be a player or an entire faction) should be able to grab loot from the loot chest
- In the config there is an option to just instantly give it to the player (Watch out with full inventories!)
