### ISSUE TITLE
Error compiling Plugin

### ISSUE THREAD

**Issue by xXkguyXx** [SubSide/KOTH#28]
Hello, I'm new with maven and do not really use it, When i import the project as a moven project i get this problem : http://prntscr.com/d6fo1o

and along with that a bunch of other problems like vanishPlugin cannot be resolved to a type, VanishManager cannot be resolved to a type etc,

Thanks

**Comment by SubSide** [comment]
Beside the maven dependencies you need to include some dependencies on your own
![screenshot_9](https://cloud.githubusercontent.com/assets/4353101/20262818/38a374a4-aa64-11e6-94fa-4fc1686c6a9f.png)

The reason for this is because not all plugins have a maven repository or is free to download.

**Comment by xXkguyXx** [comment]
ah aright Thanks
