### ISSUE TITLE
FeatherBoard  Placeholder not working

### ISSUE THREAD

**Issue by customcore** [SubSide/KOTH#29]
so when i try to add add the variable it doesn't work i not to sure why wondering if you could help me looks like this : http://prntscr.com/d7pn0t  and that's what it says the placeholder is.

**Comment by SubSide** [comment]
Featherboard allows PlaceholderAPI placeholders through the use of a prefix: placeholderapi_

So for koth_name it would be: 
{placeholderapi_koth_name}

**Comment by customcore** [comment]
i sorry for bugging you but its still not working : http://prntscr.com/d85nf7 and it comes up with this on scoreboard: http://prntscr.com/d85nke

**Comment by SubSide** [comment]
Try updating Featherboard, in one of the versions it had an issue where the PlaceholderAPI stopped working.

**Comment by customcore** [comment]
iv tried featherboard on vesion 3.11.1 and 3.12.0 both of them dont work.

**Comment by SubSide** [comment]
Hmmh, this seems to be an issue on Featherboards end or PlaceholderAPI's end.
Try /papi reload, if that doesn't work check if there are any errors in console.

**Comment by SubSide** [comment]
Reopen this if problems persist.
