### ISSUE TITLE
Koth Ideas Repost

### ISSUE THREAD

**Issue by Laos1996** [SubSide/KOTH#30]
Hey, once again I strike with ideas, when players do /koth schedule, could you make it, so it lists koths *only* (option in config to toggle yes or no this option) for current day? Like because, when they do koth schedule now, I got koths almost every hour, they cant even see which timezone koths are from ^^
Also, can you, or can I already edit lang file, so that at the bottom of /koth schedule it will say "Next koth will be in XX:XX"

Also, for "Next koth will be in XX:XX" there could be command like /koth next (Which I'd then use alt cmd /nextkoth :p )

Another less important idea, but might be cool, KOTH schedule place rotation, which means is,
instead of marking schedules with koth, you mark it with rotation, and then in config you set for each rotation which koths you want to be listed, and then it randomly sets one koth to be on schedule ^^

**Comment by SubSide** [comment]
I'll see what I can do! Nice ideas :)

**Comment by SubSide** [comment]
Most of them has been implemented except the last one, I'll take a look at it later.
06bf55da78c39f5f76dc7db82308817f2f071d97
06f32b585c3bf44af1d633217cdb99cf00a345b5
a41064fbba56a02bd4f71daee4838577b5e22d2c

**Comment by SubSide** [comment]
MapRotation has been implemented!

937eb2f0c918e7ed1f167e72e7542e4e092b5d2a
