### ISSUE TITLE
Prevent Capture spam (Must "fix")

### ISSUE THREAD

**Issue by Laos1996** [SubSide/KOTH#32]
So, there is an appearing problem with koths, if theres low interest in capturing, lets say a bad timed koth
and only one player is left to capture it, often they spam chat with leaving/joining koth area.
https://gyazo.com/e583f67411eb2de3c9c8aef9dff6bda7

Could you please add prevention so after like X ammount of times it stops printing message if same faction is recapturing koth in Y period? (Like X=5, Y=60 seconds, configurable in config for fine tunning).

**Comment by SubSide** [comment]
I have to think about a way how to implement this easily
I'll come back to this problem.

**Comment by SubSide** [comment]
You could possibly resolve this by just putting the knockTime in the config to X seconds.
This means that as soon as somebody leaves the KoTH, the KoTH will be on that cooldown. After said cooldown the KoTH will be capable again.

Will that solve your problem? :3
