### ISSUE TITLE
Scoreboard name limit

### ISSUE THREAD

**Issue by dartasen** [SubSide/KOTH#34]
Hello, with the fix https://github.com/SubSide/KOTH/issues/23, a new problem has emerged.
The scoreboard limit also affects scoreboard name (top of the scoreboard) but it's not necessary (scoreboard name may contain more than 16 characters without client crashes).
So it would be cool to be able to give back a scoreboard name longer than 16 characters.

PS : Sorry for my bad english.

**Comment by SubSide** [comment]
Added a separate option just for title.
481c0e8fbcb6538d2cf12a09dd26aecd2eb589c1
