### ISSUE TITLE
featherboard initializes koth board onJoin

### ISSUE THREAD

**Issue by elstur** [SubSide/KOTH#44]
Basically, when a user logs into a koth server, the koth table is always defaulted to. I think in the initial request is checking to see if feathboard is enabled but not if a koth is active.

Edit:
After some additional testing, this appears to only happen when a scheduled koth has ended early by someone winning. During the remaining time the koth could have been running, the koth board will show to anyone that joins the server.

**Comment by SubSide** [comment]
This issue is fixed in the latest release:

Commit:
d6bdb6a3f21ad02cf5fe347591ddffa6709dd739
