### ISSUE TITLE
Message on cap type

### ISSUE THREAD

**Issue by Laos1996** [SubSide/KOTH#45]
I have this issue REALLY OFTEN with new players;
If capturing type is set to factions, and nobody is capturing the KoTH, new players, as lazy they are, won't read my tutorial and will directly try to go and cap koth without creating faction first, so they stand like stupid pidgins complaining plugin doesent work. Therefore could you create a message if capture type is set to Factions and player who is in faction wilderness is trying to capture sending them a message "You must create faction before capturing this koth!"

**Comment by SubSide** [comment]
Hmm, I need to see how I could even accomplish this, for performance reasons I just skip players without a faction, thus making this appear means moving code around a lot. I'll keep this open and see what I can do.
