### ISSUE TITLE
Koth Not Working With Feather Board

### ISSUE THREAD

**Issue by KaPowGamingG** [SubSide/KOTH#51]
Hello SubSide, 

Your Koth plugin doesn't work with featherboard i have eveything setup, there are no errors in chat when i enable a koth, and ive change the koth config settings, but the default featherboard keeps showing instead of showing the koth one, 

Please help 

-Yours Faithfully KaPowGaming

**Comment by SubSide** [comment]
Sorry for reacting so late. Could you show me your config? Or did you manage to fix it already?
