### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by jackbritton1** [SubSide/KOTH#54]
import subside.plugins.koth.events.KothEndEvent;
import subside.plugins.koth.events.KothStartEvent;
i get errors with those imports

**Comment by SubSide** [comment]
Could you elaborate on this?

**Comment by jackbritton1** [comment]
https://gyazo.com/78a64495ede448e2963570515fc5a1bc
https://gyazo.com/0bce2ec3331279457f6e538673fbe31c

its for a board on the side to show the faction members and the power

**Comment by jackbritton1** [comment]
i managed to fix it but it flickers

**Comment by SubSide** [comment]
What flickers?
