### ISSUE TITLE
1.11.2 Spigot Init Error

### ISSUE THREAD

**Issue by ThatGamerBlue** [SubSide/KOTH#59]
http://pastebin.com/uXDt90uQ

KoTH version 1.4.6, spigot version 1.11.2-R0.1-SNAPSHOT.

The error is caused by the fact that you call `trigger()` before initializing `activeModules` causing an NPE (my theory).

**Comment by SubSide** [comment]
Could you try to do a restart?

**Comment by ThatGamerBlue** [comment]
Works now, that's weird.
