### ISSUE TITLE
Can't find main class

### ISSUE THREAD

**Issue by NighteranceMC** [SubSide/KOTH#63]
Hello! Good job with plugin!
I wanted to make it a bit different by adding one feature, but i got stuck a bit.
When I got this in my eclipse, I tryed to export and launch server, it said it could not find main class, altough path was correct ( i didnt change anything there tbh ). Know why it could be doing like that?

**Comment by NighteranceMC** [comment]
I checked all folders on export, but did not see there main class, should there be?

**Comment by SubSide** [comment]
You could try to create a new eclipse project, and then dragging the class files in the project :3

**Comment by SubSide** [comment]
If it can't find the main class, try opening the jar with winrar. It should have a map in it called "subside", not "src". If it is "src" instead, you can try removing the "src" folder in between. This does end up with a big difference in the repository, so you won't be able to push or pull with git anymore.

Or you need to find online a way to use the src map.

**Comment by NighteranceMC** [comment]
Tryed creating new eclipse project and dragging the class files, did not work :(

Opened jar with winrar, it had src, tryed to remove src. Did not work as well for some reason. Any other ideas?

**Comment by SubSide** [comment]
All errors look like they are errors (Except the dependency errors like Featherboard) because you didn't include the correct spigot.jar

Make sure the spigot.jar is of the version 1.9 or higher.

**Comment by NighteranceMC** [comment]
Okay, when I will get home I will change the version of spigot to 1.9 (but plugin will still work with 1.8.8, right?)

About dependencies - do I need them If i won't be using them? For example festherboard?

**Comment by SubSide** [comment]
You can also just remove the BossBarAPI hook. Then you can stay in 1.8 ;)

You don't need the dependencies no, you do need to remove the code for those dependencies though.

**Comment by SubSide** [comment]
This got resolved through Skype ^^
