### ISSUE TITLE
KoTH not capping

### ISSUE THREAD

**Issue by grandmen123** [SubSide/KOTH#74]
Hey there,

So I've been setting up KoTH for a customer, they are the ones that purchased it.
I have encountered a huge issue, no matter how many times I edit the koth location/delete the koth and re-install the plugin I cannot Capture the koth. I believe it is due to us using 1.8 on the server. 

Hopefully there is something that can be done about this. 

Regards,
            Grandmen123

**Comment by SubSide** [comment]
I recommend you first taking a look here: http://dev.thomasvdbulk.nl/KoTH/faq#capture :)

**Comment by grandmen123** [comment]
I've disabled newbie protection on PvPManager & I'm on a faction other then wilderness/warzone/safezone and I've also followed the exact steps on how to create a KoTH yet nothing works.

**Comment by SubSide** [comment]
Add me on Skype and I'll join the server for a moment :)

**Comment by grandmen123** [comment]
What's your Skype & IGN?

**Comment by SubSide** [comment]
"subside." with the .

IGN: SubSideNL

**Comment by SubSide** [comment]
Issue was having an outdated version of PvPManager which hasn't have the API added yet.
Solved it by disabling the PvPManager hook in the config as they weren't using the newbie protection anyways :)
