### ISSUE TITLE
Documentation for old scoreboard?

### ISSUE THREAD

**Issue by mattyokan** [SubSide/KOTH#79]
Hello,

Just wondering if @SubSide would be able to add back the scoreboard documentation for the old scoreboard - I can't find the placeholder for the capping player anywhere and I have to use the old scoreboard plugin.

Hope you'll be able to add this!

**Comment by SubSide** [comment]
For now:
%capper% = capping player/faction
%koth% = Name of the KoTH capping
%x%, %y%, and %z% for the coordinates
%m% minutes capped, %s% seconds capped
%ml% minutes left, %sl% seconds left.

The rest can be figured out from here:
https://github.com/SubSide/KOTH/blob/development/src/subside/plugins/koth/utils/MessageBuilder.java
