### ISSUE TITLE
not able to maven it

### ISSUE THREAD

**Issue by Twi5TeD** [SubSide/KOTH#8]
i cloned it and tried mavening it but it didnt work any help or have you not setup maven for it?

**Comment by SubSide** [comment]
I used a combination of maven and spigot to accomplish an environment that supported both 1.7 and 1.8+, since trying to include both versions through the workspace ended up with errors popping up about duplicate methods, and there was no 1.7 maven (as far as I knew), so I included the spigot 1.7 version just through the workspace, and 1.8+ through maven.

Sorry for making it so confusing x3

**Comment by Twi5TeD** [comment]
how would i clone a 1.8 version?

**Comment by SubSide** [comment]
I tried it myself and got it working.

Using Eclipse I did the following to get the latest development version working:
I cloned the code and executed Eclipse in the same folder and created the project there.
Through properties I added the following plugins to the build path in libraries:
- MassiveCore
- Factions
- FactionsUUID
- Worldedit
- Spigot 1.7.10
- Lombok

I hope this helps!

**Comment by Twi5TeD** [comment]
did you clone it by going to import and git?

**Comment by SubSide** [comment]
No, I didn't, I used git to clone it, and after that I opened the eclipse
workspace in there

**Comment by Twi5TeD** [comment]
are you not able to just git clone https://github.com/SubSide/KOTH.git and then mvn clean install ?

**Comment by SubSide** [comment]
I'm afraid that is not the case :\
I never got into maven, I only used it to fix the compatibility issue and
give 1.7 support.

**Comment by Twi5TeD** [comment]
ah i've never tried that other way so  wouldn't know what to do :/

**Comment by SubSide** [comment]
Well, it'a midnight right now, and I need to get up at 6 tomorrow, so I'm
going to sleep right now. But maybe I can record a quick video tomorrow
showing you how I did it ;)

**Comment by Twi5TeD** [comment]
alright thanks :)

**Comment by Twi5TeD** [comment]
Did you end up making a video :)

**Comment by SubSide** [comment]
Oh man, I'm so sorry!
I haven't had the time to make one yet, last weeks of school ar a b***.
This weekend I should have the time to make one.

Once again, I'm so sorry ;3

**Comment by Twi5TeD** [comment]
that's fine take your time :)

**Comment by SubSide** [comment]
I actually had some free time after a test, here you go https://youtu.be/ZOyXsArDKQs

**Comment by Twi5TeD** [comment]
thanks

**Comment by Twi5TeD** [comment]
`    public static Capper getFromUniqueName(String name){
        return new CappingFactionUUID(com.massivecraft.factions.Factions.getInstance().getFactionById(name));
    }`

The method getInstance() is undefined for the type Factions	CappingFactionUUID.java	/KOTH/src/subside/plugins/koth/adapter/captypes	line 95

how can i fix this?

**Comment by SubSide** [comment]
You propably didn't clone the development branch but the master, the master is using a 1.7, outdated version of Factions, it's just the matter finding the correct one, and to be honest, I can't remember which one that is xP

You have more luck cloning the development branch

**Comment by Twi5TeD** [comment]
i used the latest update from spigot and could you link me to the dev branch?

**Comment by SubSide** [comment]
just switch in git to the development branch :3

**Comment by Twi5TeD** [comment]
I did do I did git clone -b development then the link

**Comment by Twi5TeD** [comment]
It may just be the factions plugin I used since I used latest version stuff could of changed

**Comment by Twi5TeD** [comment]
would you be able to check what factionuuid you used?

**Comment by SubSide** [comment]
Currently I'm using: 1.6.9.5-U0.1.18-b302
