### ISSUE TITLE
Placeholders on Holographic DIsplay isnt working

### ISSUE THREAD

**Issue by ExoticPlayz10** [SubSide/KOTH#82]
Hey, im using the latest update for Koth and the latest update for the KOTH extension and HGD. For some reason i cant get any of the place holders to work on the hologram. please help!
![2017-06-25_20 26 39](https://user-images.githubusercontent.com/19506584/27520995-a387ba20-59e4-11e7-89ad-9e1c743a8036.png)

**Comment by SubSide** [comment]
To make my placeholders work with Holographic Displays, you need a few things, you need the PlaceholderAPI. Then as bridge between the PlaceholderAPI and Holographic Displays, you need Holographic Extension.
Make sure you read the Holographic Extension page though, as I recall it requires ProtocolLib, and the placeholders from the PlaceholderAPI are in a different format than %%'s
