### ISSUE TITLE
KoTH works but capping does not

### ISSUE THREAD

**Issue by CorruptedFile123** [SubSide/KOTH#83]
So, i recently got the new update of koth and installed it. I tested it with my old configuration and everything worked. Except, capping koth. I reset my folder and then still nothing happens. I can create koth, but i cannot cap it. I've done everything in my power to see  whats happening. I've tested configurations, /koth tp <koth>, etc. Please help me. 

CONSOLE MESSAGE:
https://gyazo.com/e4f83df70e18d47f7b31b20735d19e1e

**Comment by SubSide** [comment]
This is a little issue where my plugin prioritizes the McMMO hook over the Factions hook.
Disabling the McMMO hook in the config should do the trick.

**Comment by SubSide** [comment]
And for the console error, I recommend not using \'s
If you do have the need for \'s, you should do \\ to make it work. It will end up with just a single \
This is something that has to do with escaping. :3

**Comment by Splurgies** [comment]
I am also having the same problem but these method to fix it do not work for me bur i get no console errors it just does not let me cap!

**Comment by SubSide** [comment]
Try these first :)

http://dev.thomasvdbulk.nl/KoTH/faq#capture

**Comment by SubSide** [comment]
Should be fixed in latest version :3
