### ISSUE TITLE
Wont let me start a koth?

### ISSUE THREAD

**Issue by KillauraHacks** [SubSide/KOTH#84]
Version: Latest
-
Issue: Whenever I try to start a koth it pops up with a red error message all the other commands work except /koth start (KothName)
-
Error Message: An internal error occurred while attempting to perform this command
-
Extra Info: Koth is named NorthWest, Spigot username is KillauraHacks

**Comment by SubSide** [comment]
When you get the error message internal error occured, it means you have an error message in the console. Can you paste that error in here?

**Comment by KillauraHacks** [comment]
It apparently fixed it self if it happens again ill post

**Comment by KillauraHacks** [comment]
There is another problem though I selected the area with world edit and then it doesnt register me in the koth area when I start it please help am i not using the right tool or something

**Comment by SubSide** [comment]
Try disabling mcmmo in the config

If that doesn't work try this:
http://dev.thomasvdbulk.nl/KoTH/faq#capture

**Comment by SubSide** [comment]
Latest update should fix the mcmmo issue at least
