### ISSUE TITLE
Add GriefPreventionPlus as group plugin

### ISSUE THREAD

**Issue by SubSide** [SubSide/KOTH#86]
https://github.com/KaiKikuchi/GriefPreventionPlus-Cities

**Comment by CheatSupport** [comment]
lol

**Comment by SubSide** [comment]
I like to have everything that I have to do at 1 place instead of spread around all over spigot x)

**Comment by SubSide** [comment]
In the current state of the code from GPP-Cities it is for me not possible to add support for this without resorting to reflection, which I do not want to use in my plugin.

https://github.com/KaiKikuchi/GriefPreventionPlus-Cities/blob/master/src/main/java/net/kaikk/mc/gppcities/DataStore.java#L51
This variable must be public or I need to have access to a getter for me to get this working.
