### ISSUE TITLE
Duplicating Loot

### ISSUE THREAD

**Issue by JoeDon16** [SubSide/KOTH#9]
Players can duplicate loot from /koth loot by shift right clicking and closing the menu fast. They are NOT ghost items also. I removed the perm for them but just letting you know that it's there.

**Comment by SubSide** [comment]
Ouch, that is a very serious issue, I'll try to replicate it and fix it ASAP

**Comment by SubSide** [comment]
Over the last couple of days I have tried to reproduce said bug, but was not able to reproduce it on my local server :3
If you could show like a video on an account that is not OP or creative that would help a lot!
