### ISSUE TITLE
Issue with the timezones.

### ISSUE THREAD

**Issue by Potanz** [SubSide/KOTH#90]
I'm not sure which timezone to put for California; PST time. I tried PST; US/PACIFIC. Those two didn't work for the KoTH time zones and they never start at 7 even though the schedule is set then. It should be an easy fix, hope someone can give me an answer thanks :P

**Comment by SubSide** [comment]
Setting up timezones can be a bitch, use this walkthrough to get the time working for you:
http://dev.thomasvdbulk.nl/KoTH/faq#timezones
